export const TOGGLE_SELECTED_PARAMETER = 'TOGGLE_SELECTED_PARAMETER';
export const DELETE_SELECTED_PARAMETER = 'DELETE_SELECTED_PARAMETER';
export const ADD_VALUES_TO_SELECTED_PARAMETERS = 'ADD_VALUES_TO_SELECTED_PARAMETERS';
export const SET_NEW_CONFIGURATION = 'SET_NEW_CONFIGURATION';
export const CLEAN_STATE = 'CLEAN_STATE';
export const SORT_SELECTED_PARAMETERS = 'SORT_SELECTED_PARAMETERS';
export const SORT_CATEGORIES = 'SORT_CATEGORIES';
export const SAVE_CHANGED = 'SAVE_CHANGED';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';

export const SET_DEVICES = 'SET_DEVICES';
export const SET_DEVICE_WITH_DESCRIPTION = 'SET_DEVICE_WITH_DESCRIPTION';
export const DELETE_DEVICES = 'DELETE_DEVICES';